---
id: Tree
name: Tree
full: Tree rendering library
description: >-
  A library providing tree views of hierarchical information. It allows for
  expanding/collapsing of branches and maintains their state.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Tree
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: developer
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/exception: ^3
      horde/url: ^3
      horde/util: ^3
  optional:
    ext:
      gettext: '*'
